name: Python CI

on:
  push:
    branches:
        - 'no-ci-branch'  
  pull_request:
    branches:
        - 'no-ci-branch'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
        # Check out code from the repository
    - name: Check out the code
      uses: actions/checkout@v4

    # Setup python Environment
    - name: Set up python 
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    # Installing dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run Test
    - name: Run test
      run: pytest
